### ISSUE TITLE
Feature request: Disable tooltip close events

### ISSUE THREAD

**Issue by jacobsvante** [datuhealth/isotip#20]
It would be nice if there was the possibility to turn off the close events in case one only wants to close the tooltip under certain conditions. I tried to modify isotip's code for this but I couldn't find a way to do it in a way that only affects one tooltip.

I'm thinking something along the lines of:

``` javascript
tooltip = isotip.open('.mytooltip', {noHandlers: true});
...
if (someSetOfConditions) {
    isotip.close('.mytooltip');
}
```

Or in pure-HTML, with a close button:

``` html
<div class="mytooltip" data-tooltip-content="My tooltip" data-tooltip-no-handlers>
    <div class="close-btn" data-tooltip-close-button>Close</div>
</div>
```

**Comment by mike-engel** [comment]
@jmagnusson how do you feel about the option proposed in #22?

**Comment by jacobsvante** [comment]
Hi Mike,

I like the idea, but it seems that the functionality is not actually working properly. I [changed your tests to not use autoClose](https://github.com/jmagnusson/isotip/commit/4a18ba676dee8a2fd9c9445ce198cb840296021f) but running `npm run-script test` still passes. They should fail, shouldn't they?

**Comment by mike-engel** [comment]
Yeah, they should. Let me take a look at it tonight. Thanks for checking!

**Comment by jacobsvante** [comment]
That's awesome. Thanks for taking your time.

**Comment by mike-engel** [comment]
Alright, so, there's a lot of problems with the tests. It's gonna take me some time to figure this out. Hopefully by the weekend or next week I can have this figured out.

**Comment by jacobsvante** [comment]
Okay good luck! 😊

**Comment by mike-engel** [comment]
Good news @jmagnusson—I've got the tests passing and everything seems to be working. API changed a little: `data-autoclose` is now `data-tooltip-autoclose` to be consistent. As long as you find it's working and it suits your needs, I'll get it merged in asap.

**Comment by mike-engel** [comment]
@jmagnusson Seems like the failing test is because mocha is timing out (default tooltip delay is 200ms \* 10 = 2000ms, which is conveniently the mocha timeout. If you were to do it \* 9, it's fine. I've fixed the issue with programmatic opening with `autoClose` set to false.

I have come across a potential issue, however, which is keeping them open creates a lot of potential tooltips that need to be tracked as the page scrolls. This could be terrible for performance as more are opened with autoClose set to false. Can you describe your use case for this feature?

**Comment by jacobsvante** [comment]
Let's continue the discussion in #22.
